### ISSUE TITLE
Adicionar diretórios e arquivos html a pasta do capítulo 2

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/curso_node#3]
# Motivação
O capítulo 2 abordou conteúdos como programação baseada em eventos, roteamento e o básico da programação node, através de 2 exemplos básicos. Entretanto, o segundo exemplo adicionou o roteamento de páginas utilizando arquivos estáticos no diretório `diretorio_raíz / public / rota.html` 

Dessa forma, uma vez que não estão criadas esses arquivos, nosso servidor sempre retornará o código 500 ao acessar as rotas definidas e até mesmo nas rotas não definidas, para resolver isso devemos criar o diretório public na raiz do projeto e adicionar nessa pasta, os arquivos servidos nas rotas específicadas no arquivo index.js.

## Tasks
- [x] Adicionar o diretório public
- [x] Adicionar o arquivo home.html na pasta public
- [x] Adicionar o diretório img dentro da pasta public
- [x] Adicionar o arquivo logo.png dentro da pasta img
- [x] Adicionar o arquivo 404.html dentro da pasta public
