### ISSUE TITLE
Capítulo 3

### ISSUE THREAD

**Issue by bidwolf** [Codelife-Compet/curso_node#5]
# Capítulo 3
O capítulo 3 vem com tudo nessa semana, e ele irá nos apresentar efetivamente o framework Express e mostrar como ele facilita nossa vida quando falamos de criação de servidores. Por tanto para esse capítulo, como nos posteriores deveremos concluir algumas tarefas.

## Tasks
- [x] Adicionar o repositório Capitulo_3
- [x] Instalar as dependências do capítulo em questão
- [x] Desenvolver os exemplos propostos no livro
- [x] Adicionar o arquivo notes.md ao diretório Capitulo_3
